spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  cache:
    type: none

app:
  payment-card:
    encryption:
      base64-key: dGVzdHRlc3R0ZXN0dGVzdHRlc3Qjr2Ep
    limit-per-user: 5
  internal:
    api-keys:
      user-service: user-service:key-123123
      order-service: order-service:key-321321