spring:
  application:
    name: user-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM}
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: ${SPRING_LIQUIBASE_CHANGELOG}
    default-schema: public
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000

server:
  port: 8081

app:
  payment-card:
    encryption:
      base64-key: ${APP_PAYMENT_CARD_ENCRYPTION_BASE64_KEY}
    limit-per-user: 5